shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "zsh-defer -c '{% for file in files %}source \"{{ file }}\"\n{% endfor %}'"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
